[build]
  functions = "netlify/functions"
  publish   = "."

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "IZIPAY_TEST_KEY,IZIPAY_PROD_KEY,IZIPAY_PUB_TEST_KEY,IZIPAY_PUB_PROD_KEY"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy   = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cdn.jsdelivr.net https://*.supabase.co https://static.micuentaweb.pe; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://static.micuentaweb.pe; font-src https://fonts.gstatic.com https://static.micuentaweb.pe; connect-src 'self' https://*.supabase.co https://api.the-odds-api.com https://*.netlify.app https://*.netlify.com https://api.micuentaweb.pe https://static.micuentaweb.pe; frame-src https://static.micuentaweb.pe; img-src 'self' data: https://static.micuentaweb.pe https://api.qrserver.com; object-src 'none';"
    X-Frame-Options           = "SAMEORIGIN"
    X-Content-Type-Options    = "nosniff"
    X-XSS-Protection          = "1; mode=block"
    Referrer-Policy           = "strict-origin-when-cross-origin"
    Permissions-Policy        = "camera=(), microphone=(), geolocation=(), payment=(self)"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
